### PR TITLE
Some Fixes

### PR DESCRIPTION
**Pull request by rodfersou**
* Fixed preview that stop working in some sites.
* Fixed progress bar

### CODE REVIEW

**Comment by hvelarde** [comment]
@rodfersou you are missing a line on the changelog and the upgrade step; also, notice that `ConflictError` is rising every time you do a multiple upload now.

**Comment by hvelarde** [comment]
@davilima6 I think @rodfersou is using some sort of automatic tool to add those prefixes.

**Comment by rodfersou** [comment]
@davilima6 thank you for the review, I was using sass + bourbon here with codepen.io to generate this css.. I tried with postcss, but just with a web tool it didn't work fine.. maybe I need to add postcss by hand later

**Comment by davilima6** [comment]
Np, it's just a suggestion to dry code a bit.

**Pull request merged**
