### PR TITLE
Fix IE conditional comment

### PR DESCRIPTION
**Pull request by tcurvelo**
In `portal_javascripts`/`jsregistry.xml` conditional comments, we must not use the `if` token. Just the condition itself.
 
    

Otherwise, IE will show up the expression on the top.

if gte ie

### CODE REVIEW

**Comment by hvelarde** [comment]
@tcurvelo you're missing a line on the changelog.

**Comment by tcurvelo** [comment]
oops :sweat_smile:

**Comment by hvelarde** [comment]
@tcurvelo tests are failing, could you please take a look?

**Comment by tcurvelo** [comment]
@hvelarde Sure

**Comment by tcurvelo** [comment]
Tests are now passing in #43

**Pull request merged**
